Vagrant.configure("2") do |config|
  # config.vm.provision :shell, inline: "echo A"
  # These two lines are the global settings
  # You can keep it or remove it as well
  
  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/bionic64"
    web1.vm.network "private_network", ip: "192.168.33.15"
    web1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    web1.vm.provision "shell", inline: <<-SHELL
       sudo apt update -y
       sudo apt install apache2 wget unzip -y
       cd /tmp/
       wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip
       unzip -o 2135_mini_finance.zip
       cp -r /tmp/2135_mini_finance/* /var/www/html/
       systemctl restart apache2
    SHELL
  end

  config.vm.define "db1" do |db1|
    db1.vm.box = "geerlingguy/centos7"
    db1.vm.network "private_network", ip: "192.168.33.16"
    db1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    db1.vm.provision "shell", inline: <<-SHELL
      yum install mariadb-server -y
      systemctl start mariadb
      systemctl enable mariadb
      mysql -u root -e ' CREATE DATABASE wordpress;'
      mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "admin1234";'
      mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
      mysql -u root -e 'FLUSH PRIVILEGES;'
      systemctl restart mariadb
    SHELL
  end
end
